services:
  plan-engine:
    image: orra-plan-engine-sdk-valid
    container_name: orra-peng-sdk-valid
    build:
      context: ../../planengine
      dockerfile: Dockerfile
      target: final
    environment:
      - PORT=8005
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - sdk-test-network

  sdk-test-harness:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orra-sdk-test-harness
    environment:
      - PLAN_ENGINE_URL=http://plan-engine:8005
      - SDK_TEST_HARNESS_PORT=8006
      - SDK_CONTRACT_PATH=/app/contracts/sdk.yaml
    ports:
      - "8006:8006"
    depends_on:
      plan-engine:
        condition: service_healthy
    networks:
      - sdk-test-network
    volumes:
      - ${PWD}/contracts:/app/contracts

networks:
  sdk-test-network:
    name: orra-sdk-test-network
