version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/controlplane"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "go"
  - package-ecosystem: "gomod"
    directory: "/cli"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "npm"
    directory: "/sdks/js"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
