services:
  inventory-mgr:
    container_name: orra-inventory-mgr
    build:
      context: .
    ports:
      - "3300:3300"
    environment:
      - ORRA_URL=http://host.docker.internal:8005
      - ORRA_API_KEY=${ORRA_API_KEY}
      - DEMO_REVERT_FAIL=${DEMO_REVERT_FAIL}
      - ORRA_SERVICE_KEY_PATH=/app/data/orra-service-key.json
      - ORRA_LOG_LEVEL=trace
      - ORRA_LOGGING=true
      - NODE_ENV=development
    volumes:
      - ./.orra-data:/app/data
