services:
  delivery-agent:
    container_name: orra-delivery-agent
    build:
      context: .
    ports:
      - "3100:3100"
    environment:
      - ORRA_URL=http://host.docker.internal:8005
      - ORRA_API_KEY=${ORRA_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - DEMO_FAIL=${DEMO_FAIL}
      - ORRA_SERVICE_KEY_PATH=/app/data/orra-service-key.json
      - ORRA_LOG_LEVEL=trace
      - ORRA_LOGGING=true
      - NODE_ENV=development
    volumes:
      - ./.orra-data:/app/data
