services:
  echo-service:
    container_name: orra-echo-service-js
    build:
      context: .
    ports:
      - "3400:3400"
    environment:
      - ORRA_URL=http://host.docker.internal:8005
      - ORRA_API_KEY=${ORRA_API_KEY}
      - ORRA_SERVICE_KEY_PATH=/app/data/orra-service-key.json
      - ORRA_LOG_LEVEL=debug
      - ORRA_LOGGING=true
      - NODE_ENV=development
    volumes:
      - ./.orra-data:/app/data
